title: Tallneck test
language: en

copyright: "Copyright (c) 2024 John Toniutti"

# For jekyll-seo-tag
author: John Toniutti
tagline: "Tallneck test | This a tagline"
description: "This is a description"
url: "https://jotonedev.github.io/tallneck-test"

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      image: "/assets/images/default.webp"
      seo:
        type: BlogPosting
  - scope:
      type: "projects"
    values:
      layout: "project"
      image: "/assets/images/default.webp"
      seo:
        type: CreativeWork

sitemap: true

seo:
  type: BlogPosting

feed:
  posts_limit: 20
  disable_in_development: true

sass:
  style: compressed
  sass_dir: _sass


cloudflare: "bb92f520037c4286aea634050df09d74"

# Project folder
collections:
  projects:
    output: true

# Build settings
theme: jekyll-theme-tallneck
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
